const bio = [
  "Full Stack Web Developer with skills in Ruby on Rails, JavaScript, and React alongside a background in professional audio, music technology and as a touring musician. I discovered web development when searching for alternative ways to express ideas and create immersive experiences. When I found coding I realised that I had found my natural medium in which to create.",
  "I am a classically trained musician who has never quite fitted in the classical musician mold. After growing up as a big fish in a small pond, I trotted off to conservatoire and realised in the first summer holiday that I was not quite in the same mindset as the rest of the school; I had organised to tick off a Major Life Goal but my teachers were horrified at the idea. They didn't think they spending the summer working in Disneyworld, Florida, was at all what a diligent student should be up to.",
  "Since then I have continued to be drawn to the 'alternative' option. After I graduated the Royal College of Music, I chanced upon an advert looking for circus musicians. I was suddenly working with people I could never have hoped to meet in my previous lifestyle. They opened my eyes to the wealth of amazing variety which exists in the world. That winter I went to Scotland to learn about horses with an equestrian theatre company. I ended up becoming the musical director for their winter season but after the run, I went to Spain to really learn about horses. Fun fact: I can ride a horse whilst playing the recorder.",
  "After a second year with my first circus, I decided I was ready to go back to study but really make the most of it this time. I chose Berklee College of Music due to the contrasting nature of my undergrad conservatoire. I stayed a second year because I fell in love with the mad technology they had there so I took the chance to concentrate on learning how to use it.",
  "After Berklee, I went live in the USA to intern in recording studios for as long as my visa lasted and then accepted a job as Head Technician at a 5* resort in Greece. That job taught me that no matter how great the job is on paper, you need to be surrounded by the right people to make it a good experience. Hence I ran back to the circus",
  "There, I spent my hours off-stage trying new things. None really stuck but then I hit on programming. I quickly fell in love with my new craft and committed to finish my tour and then devote the following year to studying Fullstack Web Development with Flatiron School.",
  "Since graduating Flatiron I have been working as a Technical Coach with them - a wonderful opportunity to solidify my skills and also develop an unexpected passion for communication of code."
]

export default bio
